#!/usr/bin/env bash
# Runs the apply path on both platforms against a real bundle pair and a set of deliberately
# malformed archives.
#
# The sources under verify/*/src are symlinks to the shipping ones, so this exercises the code that
# actually runs on a device rather than a copy of it. Two substitutions remain and are the limits of
# what this proves: GraftPlugin is reduced to the two error constants it contributes, derived from
# the shipping file at build time so they cannot drift, and Android's org.json is stood in for by the
# reference implementation.
set -euo pipefail

FIXTURES="${FIXTURES:-}"
[ -n "$FIXTURES" ] || {
  cat >&2 <<'USAGE'
usage: FIXTURES=<dir> verify/run.sh

The fixture directory needs two built bundles and a patch between them:

  pt-a/  pt-b/        bundle directories, each with a graft-manifest.json
  patch.gpz           graft patch --old pt-a --new pt-b --out patch.gpz

then, from that directory:

  node <graft>/tools/patch-failure-cases.mjs

which derives the malformed archives every case below depends on. Use a realistic bundle — a
one-file marker exercises none of the pairing or cascade behaviour that makes this worth testing.
USAGE
  exit 2
}

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CACHE="${TMPDIR:-/tmp}/graft-verify-jars"

for name in patch.gpz bad-truncated.gpz bad-payload.gpz bad-missing-op.gpz bad-base.gpz bad-traversal.gpz bad-swapped.gpz; do
  [ -f "$FIXTURES/$name" ] || {
    echo "error: $FIXTURES/$name is missing — run tools/patch-failure-cases.mjs first" >&2
    exit 1
  }
done

echo "=== iOS (ZSTD_DCtx_refPrefix) ==="
(cd "$ROOT/verify/swift" && FIXTURES="$FIXTURES" swift run -c release 2>&1 |
  grep -E "^(PASS|FAIL|ALL|[0-9]+ CASE|manifest:)")

echo
echo "=== Android (zstd-jni) ==="
mkdir -p "$CACHE"
fetch() {
  [ -f "$CACHE/$1" ] || curl -fsSL -o "$CACHE/$1" "$2"
}
fetch zstd-jni.jar https://repo1.maven.org/maven2/com/github/luben/zstd-jni/1.5.7-5/zstd-jni-1.5.7-5.jar
fetch json.jar https://repo1.maven.org/maven2/org/json/json/20250107/json-20250107.jar
# androidx is published to Google's Maven, not Central.
fetch annotation.jar https://maven.google.com/androidx/annotation/annotation-jvm/1.9.1/annotation-jvm-1.9.1.jar

# Derived from the shipping GraftPlugin so the constants cannot drift from the ones on device.
python3 - "$ROOT/android/src/main/java/com/risemaxi/graft/GraftPlugin.java" "$ROOT/verify/java/src/com/risemaxi/graft/GraftPlugin.java" <<'PY'
import io, re, sys
real = io.open(sys.argv[1], encoding="utf-8").read()
lines = []
for name in ["ERROR_PATCH_CHECKSUM_MISMATCH", "ERROR_PATCH_FAILED"]:
    match = re.search(r'public static final String %s = ("(?:[^"\\]|\\.)*");' % name, real)
    assert match, f"{name} is no longer declared in GraftPlugin"
    lines.append("    public static final String %s = %s;" % (name, match.group(1)))
io.open(sys.argv[2], "w", encoding="utf-8").write(
    "package com.risemaxi.graft;\n\n"
    "// Generated by verify/run.sh from the shipping GraftPlugin. Do not edit.\n"
    "final class GraftPlugin {\n" + "\n".join(lines) + "\n}\n"
)
PY

CP="$CACHE/zstd-jni.jar:$CACHE/json.jar:$CACHE/annotation.jar"
OUT="$ROOT/verify/java/out"
rm -rf "$OUT"
javac -nowarn -cp "$CP" -d "$OUT" $(find "$ROOT/verify/java/src" -name "*.java")
FIXTURES="$FIXTURES" java -cp "$CP:$OUT" com.risemaxi.graft.Harness |
  grep -E "^(PASS|FAIL|ALL|[0-9]+ CASE|manifest:)"
